name: gaspul
description: "Gerakan Aktif Sistematis Pelayanan Unggul"
publish_to: 'none'

version: 1.0.0+5

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.6
  google_fonts: ^6.2.1
  flutter_tts: ^3.7.0
  flutter_inappwebview: ^6.1.5
  file_picker: ^8.0.0
  lottie: ^3.1.2
  qr_flutter: ^4.0.0
  pdfx: ^2.6.0
  fl_chart: ^1.1.1
  http: ^1.1.0            # ✅ dipindahkan ke dependencies
  pdf: ^3.11.3           # ✅ dipindahkan ke dependencies
  printing: ^5.11.0      # ✅ dipindahkan ke dependencies
  intl: 0.17.0
  animated_flip_counter: ^0.3.4
  confetti: ^0.8.0
  responsive_framework: ^1.5.1
  path: ^1.8.3
  dio: ^5.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: 0.14.4

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/app_icon_gaspul.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/app_icon_gaspul.png
    - assets/images/logo_gaspul.png
    - assets/images/Logo KUA.png
    - assets/images/Logo Layanan Internal.png
    - assets/images/Logo Layanan Kabupaten.png
    - assets/images/Logo Layanan Pendidikan.png
    - assets/images/Logo Pelayanan Publik.png
    - assets/images/Logo Rubrik.png
    - assets/images/Geometric Pattern.png
    - assets/images/Logo Bagian Tata Usaha.png
    - assets/images/Logo Bidang Penyelenggaraan Haji dan Umrah.png
    - assets/images/Logo Bidang Pendidikan Madrasah.png
    - assets/images/Logo Bidang Bimbingan Masyarakat Islam.png
    - assets/images/Logo Bimas Kristen.png
    - assets/images/Logo Bimas Katolik.png
    - assets/images/Logo Bimas Hindu.png
    - assets/images/Logo Bimas Buddha.png
    - assets/images/Logo Absensi.png
    - assets/images/logo Bengkel IT.png
    - assets/images/Logo Kabupaten Majene.png
    - assets/images/Logo Kabupaten Mamasa.png
    - assets/images/Logo Kabupaten Mamuju.png
    - assets/images/Logo Kabupaten Mamuju Tengah.png
    - assets/images/Logo Kabupaten Pasangkayu.png
    - assets/images/Logo Kabupaten Polewali Mandar.png
    - assets/images/Logo Guru.png
    - assets/images/Logo Pencatatan Nikah.png
    - assets/images/Logo Podcast.png
    - assets/images/Logo Cuti.png
    - assets/images/Logo RKB.png
    - assets/images/Logo Gembira.png
    - assets/images/Logo SIKEMBAR.png
    - assets/images/Logo KEMENAG.png
    - assets/images/Pattern Down.png
    - assets/images/Pattern Up.png
    - assets/images/Logo Sihabba.png
    - assets/images/Logo Pengaduan Masyarakat.png
    - assets/images/Logo Pengaduan Pelayanan.png
    - assets/images/Logo Pengaduan.png
    - assets/images/logo Dumas ITJEN.png
    - assets/images/Logo Emis.png
    - assets/images/logo LAPOR.png
    - assets/images/Logo SIAGA.png
    - assets/images/logo Simkah.png
    - assets/images/Logo SIMPATIKA.png
    - assets/images/Logo PDUM.png
    - assets/images/Logo GTK Madrasah.png
    - assets/lottie/Under_Maintenance.json
    - assets/lottie/Speed.json
    - assets/images/Logo Statistik Pelayanan.png
    - assets/images/Logo Status Layanan.png
    - assets/images/Logo Ambil Antrian.png
    - assets/images/Logo Layanan Konsultasi.png
    - assets/lottie/Success_Send.json